### ISSUE TITLE
扫描完歌曲之后 点 列表中的歌曲 蹦了

### ISSUE THREAD

**Issue by ilikt** [Sole2016/LocalMusic#3]

**Comment by Sole2016** [comment]
可以提供下崩溃日志吗？在手机存储/内存卡的Download目录下有个music_error_log.txt

**Comment by ilikt** [comment]
---- 428456:10:00 ----
java.lang.Error: java.io.IOException: setDataSource failed.
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: setDataSource failed.
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1251)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1224)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1191)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1087)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1029)
	at com.zy.ppmusic.utils.i.b(SourceFile:117)
	at com.zy.ppmusic.utils.i.a(SourceFile:79)
	at com.zy.ppmusic.service.MediaService$e.run(SourceFile:572)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	... 2 more

**Comment by ilikt** [comment]
抱歉 刚看到 之前赶项目比较忙
